version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    target-branch: main
    commit-message:
      prefix: deps
      prefix-development: deps(dev)

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci(deps)
    schedule:
      interval: weekly
