name: Run DCLint with Reviewdog
description: 🐶 Run DCLint with Reviewdog on pull requests to improve code review experience
author: Sergey Kupletsky <s.kupletsky@gmail.com>
branding:
  icon: check
  color: blue

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'dclint'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-code-suggestions].
      Default is github-pr-check.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  dclint_flags:
    description: 'dclint flags. (dclint <dclint_flags>)'
    default: ''

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: sh
      env:
        REVIEWDOG_VERSION: v0.20.3
        DCLINT_VERSION: 2.2.2
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_DCLINT_FLAGS: ${{ inputs.dclint_flags }}
