name: DCLint Docker Action
description: A GitHub Action for validating and enforcing best practices in Docker Compose files with DCLint Docker Image
author: Sergey Kupletsky <s.kupletsky@gmail.com>
branding:
  icon: check
  color: blue

inputs:
  args:
    description: CLI arguments to pass to DCLint
    required: false
    default: '["."]'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ fromJson(inputs.args) }}
